### ISSUE TITLE
Sometimes scenes are triggern during system startup

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.manager#13]
Depending on the scenes this can cause in bad situations, e.g.:
* All Lights are turned of
* Shutters are shutting down

Maybe this depends on connected scene buttons where the initial momentary switch remains in the pressed state during startup phase and the initial ButtonState notification triggers the connected scene?

**Comment by pLeminoq** [comment]
If the button connection is the problem this should be fixed by implementing commit openbase/bco.dal#69

**Comment by DivineThreepwood** [comment]
Bug was fixed by openbase/bco.dal#69 but review still needed.

**Comment by DivineThreepwood** [comment]
Has been fixed by filtering transitions from UNKNOWN to BUTTON_PRESSED.
