### ISSUE TITLE
Use the UnitStateAwaiter in agent test

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.manager#39]
The UnitStateAwaiter is a generic solution to wait till a unit has a specific state. It can be used in unit tests to replace the Thread.sleep() which speeds up the test.

I already used it for the AbsenceEnergySavingAgentTest. Please also use it for the other agent tests.

**Comment by TimoMichi** [comment]
All agent tests are using the UnitStateAwaiter now. 
Work is done on feature-resource-allocation branch. (72a7b65c6dcfe134192e6ce096b100d99444f152)

Might be merged to master after review.
