### ISSUE TITLE
Device Controller are updated but not registered if new ones are registered

### ISSUE THREAD

**Issue by DivineThreepwood** [openbase/bco.manager#4]
If the device manager is started and afterwards new devices are registered the device manager get informed with an device update not an new registration so the update is skipped because the device to update does not exist.

**Comment by pLeminoq** [comment]
When a new deviceUnitConfig is registered before finishing the according dalUnits are registered. The registration of a dalUnit leads to observer notification and so the new deviceUnitConfig is published without entries for the units.
So when the real finished deviceUnitConfig is published a new DeviceController is not registered but an existing one is updated. Thus to fix this bug the applyConfigUpdate method should handle changes in units of a device.

**Comment by pLeminoq** [comment]
Should be fixed by the commits openbase/jul@cf72b228a23c8a279e20d2acd27ce2ecdb0e6497, openbase/bco.dal@d22ee72b15e323633e8df30680c34801f4a1185a and openbase/bco.manager@b2b5bad3997116e9961897f6aed192d6c92ac996

**Comment by pLeminoq** [comment]
Commit openbase/bco.registry@e99413d05b508f20bd3c2af7a39a0f4a6314cba3 also fixes a bug in this procedure

**Comment by pLeminoq** [comment]
Related issue is #15
