### ISSUE TITLE
Error when generating openhab config entries for TemperatureAlarmStateServices

### ISSUE THREAD

**Issue by pLeminoq** [openbase/bco.manager#43]
These services are currently deactivated in the OpenHABItemConfigGenerator because the item entries cannot be generated.

**Comment by DivineThreepwood** [comment]
Because TemperatureAlarmStateServices are just not supported yet those are already ignored by the current implementation.
Additionally generating openhab config files will be replaced by the openhab2 platform synchronization in near future so there is no further need for addressing this issue.
